backend:
  name: auth0
  auth0_domain: dev-gpz70ghzbu23slix.auth0.com
  auth0_client_id: ykbUi1N7y4w5ivDxQfGfweyZKUp9s2OV
  auth0_audience: https://dev-gpz70ghzbu23slix.auth0.com/api/v2/
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "jobs"
    label: "Job Listings"
    folder: "content/jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Job Title", name: "title", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Job Type", name: "type", widget: "select", options: ["Full-time", "Part-time", "Remote"] }
      - { label: "Experience Level", name: "experience", widget: "select", options: ["Entry", "Mid", "Senior"] }
      - { label: "Salary Range", name: "salary", widget: "string" }
      - { label: "Job Category", name: "category", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Apply Link / Email", name: "apply", widget: "string" }

